config/routes.rb
Rails.application.routes.draw do

  root 'status#show'
  resources :mates, only: [:show,:edit,:update]
  resources :areas, only: [:edit]
  resources :duties, only: [:index,:destroy]

  post 'bot114815095:AAH0C9oMZKAEG4WMe4eZ9AmYHUZTrnJ1xCc' => 'webhooks#get_updates'
  get 'bot114815095:AAH0C9oMZKAEG4WMe4eZ9AmYHUZTrnJ1xCc' => 'webhooks#remind_of_duties'

  patch 'change_assigned_area/:id' => 'mates#change_assigned_area'

end

app/models/mate.rb
class Mate < ActiveRecord::Base
	validates :first_name, uniqueness: true
	validates :last_name, uniqueness: true
	validates :mobile_number, uniqueness: true
	validates :chat_id, uniqueness: true, allow_nil: true

	has_many :duties

	# return the current open duty
	def current_duty
		self.duties.find_by(accomplished_at: nil)
	end

  # returns next area_id out of 1..3
	def next_area_id
		next_id = self.current_duty.area.id + 1
		return next_id if (next_id <= 4)
		return 1
	end

	# notifies all mates exept the given, that a task was completed
	def notify(duty)

		Thread.new do

			maocit = File.read('data/maobibel.txt').split('+')
			last_i = maocit.length - 1

			Mate.all.each do |other_mate|
				if other_mate != self

					cit = maocit[Random.rand(last_i)]
					time = Time.zone.now.strftime('%H:%M')
					mao = 'Es ist ' + time + ' Uhr.' + "\nDas Mao-Zitat der Stunde enstammt der Quelle: " + cit
					planned = ""
					planned = "Diese Aufgabe war übrigens nicht geplant!"  if duty.due_to.nil?
					message = """\nHi #{other_mate.first_name},\n#{mate.first_name} hat grade folgendes gemacht: #{duty.area.name}.\n#{planned}\nEr hat nun #{mate.points} Punkte.\nDu hast #{other_mate.points} Punkte!\nLink: #{root_url + "##{other_mate.first_name.downcase}"}\n\n#{mao}"""
					send_message(other_mate.chat_id, message)
				end
			end

		end
	end

end

app/controllers/mates_controller.rb
class MatesController < ApplicationController

	def change_assigned_area
		@mate = Mate.find_by(id: params[:id])

		if @mate
			@mate.current_duty.update_columns(area_id: @mate.next_area_id,
											  due_to: next_sunday(@mate.current_duty.due_to - 7.days)
											  )
			@mate.reload # reload for use in view
		else
			@error = "Fehler beim Aufgabenwechsel!"
			flash[:danger] = @error
		end
	end

	def show
		if @mate = Mate.find_by(id: params[:id])
			@areas = Area.all
		else
			flash[:danger] = "Mate id nicht gefunden"
			redirect_to root_path
		end
	end

	def edit
		@mate = Mate.find_by(id: params[:id])
		@duty = @mate.current_duty
		check_mate_duty(@mate, @duty)
	end

	def update
		mate = Mate.find_by(id: params[:id])
		duty = mate.current_duty # always retrieve the current open task
		area_id = params[:area_id].to_i

		if (check = check_mate_duty(mate, duty, area_id)) == :no_duty_match # case that cleaned area wasn't assigned

			# create new duty for cleaned area for tracking purposes
			new_duty = mate.duties.create!(area_id: area_id,
									due_to: nil, 					 # mark that this wasn't an assigned task
									accomplished_by_assigned: false, # mark that this wasn't an assigned task
									accomplished_at: Time.zone.now,
									faulty: false)

			mate.update_attribute(:points, mate.points + new_duty.area.points)
			new_duty.area.update_columns(last_cleaned: Time.zone.now, clean: true)

			message = """\nSuper #{mate.first_name},\nneuer Punktestand: #{mate.points}. Weiter so :)"""
			send_message(mate.chat_id, message, last_name: mate.last_name)
			mate.notify(new_duty)

		elsif check # case that the area was assigned in current duty
			x = mate.duties.create(area_id: mate.next_area_id,
									due_to: next_sunday(duty.due_to),
									accomplished_by_assigned: true,
									accomplished_at: nil,
									faulty: false)
			if x # make sure new duty was created

				duty.update_attribute(:accomplished_at, Time.zone.now)
				duty.area.update_attribute(:clean, true)
				mate.update_attribute(:points, mate.points + duty.area.points)
				duty.area.update_columns(last_cleaned: Time.zone.now, clean: true)

				mate.reload # for access to new task in sms

				message = """\nSuper #{mate.first_name},\nneuer Punktestand: #{mate.points}.\nDeine nächste Aufgabe: #{mate.current_duty.area.name}. \nDeadline: #{mate.duties.last.due_to.strftime("%a, %d.%m")}.\nLink: #{root_url + "##{mate.first_name.downcase}"}"""

				send_message(mate.chat_id, message, last_name: mate.last_name)
				mate.notify(duty)


				@error = nil unless @error # set error to nil since it may already contain sth.
				flash[:success] = "Punkte gutgeschrieben - Neue Aufgabe zugeteilt"

			else
				@error = "Fehler beim Aufgabenerzeugen!"
				flash[:danger] = @error
			end
		end

		@area = Area.find(area_id) # used in js response
		@mate = mate.reload

		respond_to do |format|
		    format.js
		end
	end

	def next

		mate = Mate.find_by(id: params[:id])

		if(mate) then

		else
			@error = "Fehler, falscher Bewohner!"
			flash[:danger] = @error
		end


	end

	private

		# checks validity, returns false if not compliant, returns 1 if the area wasn't in the current duty, otherwise returns true
		# also sets the @error variable, for use in responses/views
		def check_mate_duty(mate, duty, area_id)
			if mate && duty # check if mate/duty were found in database
				if (mate.id != duty.mate_id) || (duty.area.id != area_id) # check if duty belongs to mate and if duty belongs to area
					@error = "Diese Aufgabe war nicht geplant! Super, #{mate.first_name}! :)"
					flash[:danger] = @error
					return :no_duty_match
		   		elsif duty.accomplished_at # if not nil, duty has already been accomplished
		   			@error = "Bereits erledigt!"
					flash[:danger] = @error
					return false
				end
				return true
			else
				@error = "Falsche User/Duty ID!"
				flash[:danger] = @error
				return false
			end
		end

		# returns date for sunday 24:00pm of current week or of next week if supplied with due_to_date before now.
		# E.g. Function is called Monday at 00:00pm, then right_now needs to be incremented to next week (+7 days) since duties are assigned weekly
		def next_sunday(due_to_date)
			right_now = Time.zone.now
			right_now += 6.days if right_now <= due_to_date # approximation should be fine, ignore edge cases for now
      return right_now + (7 - right_now.wday).days + (22 - right_now.hour).hours + (0 - right_now.min).minutes + (0 - right_now.sec).second
	  end

 end

app/helpers/mate_helper.rb
module MateHelper

	def duty_deadline(mate)
		duty = mate.current_duty
		return duty.area.name + " bis " + duty.due_to.strftime("%a, %d.%m") + " (noch " + days_till_deadline(mate) +")"
	end

	def days_till_deadline (mate)
		days = ((mate.current_duty.due_to - Time.zone.now) / 1.day).to_i
		return pluralize(days, "Tag");
	end

end

app/views/mates/_mate.html.erb
<b>
<div class="col-md-3 text-center">
		<div class="fade-in" style="margin-bottom: 30px;">
			<%= link_to image_tag(asset_path(mate.first_name.downcase + ".jpg"), class: "img-circle fade-in box-shadow", alt: "mate", width: "140", height: "140"), mate %>

			<h2 style="margin-top: 5pt; margin-bottom: 20pt"><%= mate.first_name %></h2>
			<div class="img-thumbnail" style="background-color:rgba(256, 256, 256, 0.5);">
				Geplant: <%= Area.find(mate.current_duty.area_id).name %> bis <%= mate.current_duty.due_to.strftime("%a der %d.%m") %><br>
				Punkte: <%= mate.points %><br>
				Guthaben: <%= mate.balance %> <i class="fa fa-btc"></i><br>
			</div>
		</div>

		<% area =  mate.current_duty.area %>

		<div class="fade-in2" style="margin-bottom: 50px;">
			<div class="img-thumbnail" style="color: white; background-color:rgba(0, 0, 0, 0.3);">
				<h2 style="margin-top: 0;"><%= render 'shared/area_title.mobile', area: area %></h2>
				<%= "Geputzt: " + area.last_cleaned.strftime("%a, %d.%m um %H:%M") %><br>
				Status: <%= render 'shared/label.mobile', area: area %><br>
				Sewancoins: <%= area.points %> <i class="fa fa-btc"></i>
			</div>
		</div>

</div>
</b>

app/views/mates/_mate.mobile.erb
<%= link_to image_tag(asset_path(mate.first_name.downcase + ".jpg"), class: "img-circle fade-in box-shadow", alt: "mate", width: "140", height: "140"), "##{mate.first_name.downcase}" %>

<h2 style="margin-top: 5pt; margin-bottom: 20pt"><%= mate.first_name %></h2>

<%= render 'mates/mate_list', mate: mate %>

app/views/mates/_mate_list.mobile.erb
<ul data-role="listview" data-inset="true">
	<% if mate.chat_id.nil? then %>
	<%= raw """#{'<li style="white-space: normal;"><p>Bitte verbinde deinen Telegram-Account für Notifications:</p><p><a href="https://telegram.me/kryptobot">Telegram Bot</a>!</p><p>1. Adde den Bot!</p><p>2. Schicke <b>' + mate.last_name + '</b> als Nachricht!</p></li>'}""" %>
	<% end %>
	<li><span class="due-<%= mate.id %>"><%= duty_deadline mate %></span></li>
	<li>Punkte: <span class="points-<%= mate.id %>"><%= mate.points %></span></li>
	<li>Guthaben: <span class="balance-<%= mate.id %>"><%= mate.balance %></span> <i class="fa fa-btc"></i></li>
</ul>

app/views/mates/change_assigned_area.js.erb
// show dialog located in page div in /views/status/show.mobile.erb
// show dialog located in page div in /views/status/show.mobile.erb
$("#dialog-content").text("<%= @error ? @error : "Datenbank aktualisiert! Mensch #{@mate.first_name}, neue Aufgabe, neues Glück :)" %>");
$.mobile.changePage( "#dialog", { role: "dialog", transition: "flip"} );

// update mate attributes accordingly
<% if @mate %>
$(".due-<%= @mate.id %>").text("<%= duty_deadline @mate %>");
<% end %>

app/views/mates/edit.html.erb
<div class="text-center fade-in" style="margin-top: 30%;">

<div class="img-thumbnail" style="color: white; background-color:rgba(0, 0, 0, 0.3)">
<h1 style="color: white; margin-top: 0;"><%= @mate.first_name + " – " + @duty.area.name %></h1>


<%= form_tag(mate_path(@mate), method: 'patch',class: "form-inline") do %>
    <%= hidden_field_tag('duty_id', @duty.id ) %>
    <%= submit_tag("Geputzt", class: "btn btn-primary") %>
<% end %>
</div>

</div>

app/views/mates/show.html.erb
<div class="col-md-offset-4" style="margin-top: 50px">

<%= render @mate %>

<div class="col-md-3 text-center fade-in2">

<div class="img-thumbnail" style="color: white; background-color:rgba(0, 0, 0, 0.3)" style="margin-bottom: 90px">

<p>Ich habe gereinigt:</p>

<table >
<% @areas.each do |area| %>
<tr>
<p>
<td width="80%" style="padding-bottom: .5em">
<button type="button" class="btn btn-<%= area.clean? ? 'success' : 'danger' %>" style="width: 100%"><%= area.name %></button>
</d>
<td style="padding-bottom: .5em">
<b><%= area.points %></b>
</td>
</p>
</tr>
<% end %>
</table>

</div>

</div>
</div>

app/views/mates/update.js.erb
// show dialog located in page div in /views/status/show.mobile.erb
$("#dialog-content").html('<%= @error ? @error.html_safe : "Datenbank aktualisiert!" %>');
$.mobile.changePage( "#dialog", { role: "dialog", transition: "flip"} );
// update the labels accordingly
label = $('.form-<%= @area.id %>');
label.fadeOut(300, function(){

	label.attr("class","label <%= @area.clean? ? "label-success" : "label-danger" %> form-<%= @area.id %>");
	label.text("<%= @area.clean? ? "Sauber" : "Dreckig" %>");
	label.fadeIn(800);

});
// update mate attributes accordingly

$(".points-<%= @mate.id %>").text("<%= @mate.points %>");
$(".balance-<%= @mate.id %>").text("<%= @mate.balance %>");
$(".due-<%= @mate.id %>").text("<%= duty_deadline @mate %>");